name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🆕 Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧪 Tests'
    label: 'test'
  - title: '🔧 Performance Improvements'
    label: 'perf'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: '📖 Document'
    label: 'docs'
  - title: '🚀 CI/CD'
    label: 'ci'
  - title: '🌎 Internationalization'
    label: 'translation'
  - title: 'Style'
    label: 'style'
  - title: 'Refactor'
    label: 'refactor'
  - title: 'Revert'
    label: 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES