display_name: F2fa
package_name: f2fa
maintainer:
  name: jenken827
  email: jenken827@gmail.com
priority: optional
section: utils
installed_size: 27648
icon: assets/icons/f2fa.png

keywords:
  - 2fa
  - Totp
  - Google Authenticator
  - Two-factor authentication
  - Microsoft Authenticator

generic_name: 2fa Application

categories:
  - Utility
  - Security

startup_notify: true

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml