# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 1F2E3D4C-5B6A-7988-E8D7-F6E5D4C3B2A1
display_name: F2fa
executable_name: f2fa
publisher_name: jenken827
publisher_url: https://github.com/jenken827/f2fa
install_dir_name: "C:\\Program Files\\f2fa"
output_base_filename: f2fa
create_desktop_icon: true
locales:
  - en
  - zh