name: build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build platform'
        required: true
        default: 'all'
  # push:
  #   tags:
  #     - "v*.*.*"
env:
  FLUTTER_VERSION: "3.24.5"

permissions:
  contents: write

jobs:
  build-windows:    
    if:  ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'windows' }}
    runs-on: windows-latest   
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: Build
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |          
          Invoke-WebRequest -Uri "https://github.com/jrsoftware/issrc/raw/main/Files/Languages/Unofficial/ChineseSimplified.isl" -OutFile "ChineseSimplified.isl"
          mv ChineseSimplified.isl "C:\Program Files (x86)\Inno Setup 6\Languages\"
          ./generate.bat
          dart pub global activate -s git https://github.com/jenken827/flutter_distributor.git --git-path=packages/flutter_distributor --git-ref=broken_upgrade
          flutter_distributor release --name=release1 --jobs=windows
  build-linux:
    if: ${{ github.event.inputs.platform == 'all' || github.event.inputs.platform == 'linux' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: |
          sudo apt update -y
          # flutter build dependencies
          sudo apt install -y ninja-build libgtk-3-dev libayatana-appindicator3-1 libayatana-appindicator3-dev
          # appimage build dependencies
          sudo apt install -y libfuse2 locate
          wget -O appimagetool "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x appimagetool
          sudo mv appimagetool /usr/local/bin/
      - name: Build
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash generate.sh     
          dart pub global activate -s git https://github.com/jenken827/flutter_distributor.git --git-path=packages/flutter_distributor --git-ref=broken_upgrade
          flutter_distributor release --name=release1 --skip-jobs=windows